### ISSUE TITLE
'rx' now '@reactiveX/js' ?

### ISSUE THREAD

**Issue by chriscurnow** [angular-class/angular2-webpack-starter#102]
Just started working with this starter – which is really exciting.

However I am getting lots and lots of errors. Too many to document all of them. I'm wondering if this is a result of where angular2 is up to at the moment of if I have done something wrong.

Just for one many of the examples have the following:

```javascript
import * as Rx from 'rx';
```

It appears that this should in fact be:

```javascript
import * as Rx from '@reactiveX/rxjs';
```
Also, line 34 in ac_autosuggest.ts throws an error 'zone is unknown.

```javascript
.do(zone.bind(() => this.loading.next(true)))
```

Is this because the zone module has not been loaded? If so, how do I load it?

**Comment by gdi2290** [comment]
can you submit pull-requests? I haven't updated the examples yet

**Comment by chriscurnow** [comment]
Done.
This was my first ever pull-request!!

**Comment by gdi2290** [comment]
congrats! and thanks for your help :+1:
