### ISSUE TITLE
What is traceur's role?

### ISSUE THREAD

**Issue by danhamlin** [angular-class/angular2-webpack-starter#15]
Hello,
I'm curious as to the role that traceur plays in this setup?  I've read that it is a ES6 transpiler.  Beyond that i'm not sure why it is needed here.  Is there some interplay with Typescript there?

**Comment by gdi2290** [comment]
traceur is only there until Angular 2 is fully converted to TypeScript also see https://github.com/angular/angular/issues/2140

**Comment by danhamlin** [comment]
Thanks Patrick, that makes sense.

**Comment by gdi2290** [comment]
no problem, if you have anymore questions open another issue or tweet us

**Comment by gdi2290** [comment]
I also added a faq with the answer https://github.com/angular-class/angular2-webpack-starter/commit/78002fa20f2cfeebd0b4abf8b1d1be6d3f4cf668

**Comment by gszabo** [comment]
Does this answer still hold? There seems to be no sign of traceur any more in the source code.

**Comment by gdi2290** [comment]
traceur was removed but it was there as an ES6 polyfill

**Comment by gszabo** [comment]
Ah, I see, thank you.

**Comment by gdi2290** [comment]
no problem, if you have any more issues/questions feel free to open an issue :+1:
