### ISSUE TITLE
Runtime errors in Safari

### ISSUE THREAD

**Issue by danhamlin** [angular-class/angular2-webpack-starter#17]
I guess this is known issue with traceur/ng2 that was recently fixed... https://github.com/angular/angular/issues/2163

Not sure if you are already aware, thought I'd share in case other Safari users come along.

**Comment by gdi2290** [comment]
thanks, yeah the next release will fix this

**Comment by gdi2290** [comment]
I added a faq about it until the next tagged release 
https://github.com/angular-class/angular2-webpack-starter/commit/2027712ae521f8375a7b0ae0d80ac5c779814c0c

**Comment by gdi2290** [comment]
@danhamlin thanks, this was fixed in Alpha.26 so Angular 2 right now works in Chrome (43, 44, 45), Firefox (37, 39, 40), IE 11, Safari 8, iOS 8, Android 5.1 (Chrome Mobile 39).
