### ISSUE TITLE
Broken angular2@2.0.0-alpha.19+

### ISSUE THREAD

**Issue by ShMcK** [angular-class/angular2-webpack-starter#2]
Thanks again for this project. I think if the Angular community starts to see the usefulness of Webpack over SystemJS, it'll really take off.

I noticed Webpack-seed works with versions angular2@2.0.0-alpha.13 through 18, but fails at 19+.

You might consider dropping the  ^ (or higher) dependency on Angular.

```json
 "dependencies": {
    "angular2": "2.0.0-alpha.18",
    "rtts_assert": "2.0.0-alpha.18",
    "zone.js": "^0.4.1"
  }
```

I'm not sure what causes the issue, but I hope to see a fix!

**Comment by gdi2290** [comment]
thanks! I'll update this repo later this week to alpha-19. I'm pretty sure I know what's missing

**Comment by ShMcK** [comment]
Thanks! Looks like alpha-20 is out now, as well.

**Comment by gdi2290** [comment]
@ShMcK I updated the repo to alpha 23 and typescript 1.5. Could you give it another try?

**Comment by ShMcK** [comment]
Working great, thanks!
