### ISSUE TITLE
Not compatibile with alpha29

### ISSUE THREAD

**Issue by tamascsaba** [angular-class/angular2-webpack-starter#25]
Hy!

I use angular2 alpha 29 because child router fixed, but angular2-webpack-starter based on alpha26 and not compatibile with new changes.

eg:
BrowserLocation -> LocationStrategy

**Comment by gdi2290** [comment]
@tamascsaba yeah I'm updating it now

**Comment by gdi2290** [comment]
thanks, the repo has be updated via https://github.com/angular-class/angular2-webpack-starter/commit/f1065582590c8f5bd5140ec94b97541cd78d7b50
