### ISSUE TITLE
Explain the webpack setup

### ISSUE THREAD

**Issue by gajus** [angular-class/angular2-webpack-starter#31]
In the [webpack.config.js](https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js) you have "angular2" entry.

```js
angular2': [
      'zone.js',
      'reflect-metadata',

      './src/common/BrowserDomAdapter',

      'angular2/angular2',
      'angular2/router',
      'angular2/di',
      'angular2/src/facade/browser'
],
```

I do not understand whats the purpose of bundling together the following dependencies:

* 'angular2/angular2'
* 'angular2/router'
* 'angular2/di'
* 'angular2/src/facade/browser'

into a separate script, if you require these using ES6 imports in the script itself, when you use them, e.g. https://github.com/angular-class/angular2-webpack-starter/blob/master/src/app/bootstrap.ts#L4. The end result is that you have multiple declarations of "angular2/*" and those declared as the "angular2" webpack entry are never used.

What are you using  './src/common/BrowserDomAdapter' for?

**Comment by gdi2290** [comment]
I'm using  `./src/common/BrowserDomAdapter` to ensure that the script being compile is using the correct dom adapter (I had a problem in the past where this was a problem in webpack). And the other files are not needed

**Comment by gdi2290** [comment]
I removed everything except angular2/angular2
https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js 
```
    'angular2': [
      // Angular 2 Deps
      'zone.js',
      'reflect-metadata',
      'rtts_assert/rtts_assert',
      'angular2/angular2'
    ],
```

**Comment by gajus** [comment]
I nonetheless do not understand the reason you are including angular2/angular2. Your entry point is your app script. It imports angular2/angular2 using import statement. Unless I am missing something, if you are including angular2/angular2 this way, your script does not even pick it up, i.e. dead weight.

**Comment by gdi2290** [comment]
When webpack generates the file it chunks modules together so I'm forcing Angular to remain in one file for the browser to cache.

**Comment by gajus** [comment]
Thats because you are using the plugin. This kinda defeats the purpose of the latter plugin, esp. on a small app.
