### ISSUE TITLE
File reference in autosuggest example has wrong case

### ISSUE THREAD

**Issue by andersbc** [angular-class/angular2-webpack-starter#35]
This is just a small thing, but it breaks the build:
```
WARNING in ./components/rxjs-examples/autosuggest/Search.ts
(7,27): Cannot find module './Autosuggest'. (2307)

ERROR in ./src/app/components/rxjs-examples/autosuggest/Search.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./Autosuggest in /home/anders/Dropbox/dev/itembox/code/t_angular2-webpack-starter/src/app/components/rxjs-examples/autosuggest
 @ ./src/app/components/rxjs-examples/autosuggest/Search.ts 15:20-44
```
Search.ts references `/.Autosuggest` [https://github.com/angular-class/angular2-webpack-starter/blob/master/src/app/components/rxjs-examples/autosuggest/Search.ts#L7](https://github.com/angular-class/angular2-webpack-starter/blob/master/src/app/components/rxjs-examples/autosuggest/Search.ts#L7) , but the actual file is spelled with lower case `/.autosuggest`, so it's an easy fix: either change the file name or the reference. 

It looks like the repo uses lowercase for all files in src except the ones in /autosuggest and /timeflies where the naming is a little inconsistent.

**Comment by gdi2290** [comment]
@andersbc do you think you can make a pull-request?

**Comment by SekibOmazic** [comment]
@andersbc You can edit it directly in browser.

**Comment by andersbc** [comment]
Ok.. I'll do it.. It would be my first PR though. 
What do you prefer  - changing the file name to upper case or the reference to lower case?

**Comment by gdi2290** [comment]
let's just keep it all lowercase

**Comment by andersbc** [comment]
seems reasonable.. I'll get back with the PR.
