### ISSUE TITLE
problem with todo api

### ISSUE THREAD

**Issue by csreddy** [angular-class/angular2-webpack-starter#37]
I have followed the instructions in  *Dependencies* section. I have node `v0.12.3` and npm `v2.13.2`
I see this in my chrome console `GET http://localhost:8080/api/todos 404 (Not Found)`. As the app suggests I have installed these module as well, but still no luck
`npm install express connect-history-api-fallback morgan body-parser` 

Any clues?

**Comment by gdi2290** [comment]
yeah I should have added another line. Rather than using `npm run server` run `npm run express` for the api to work.

**Comment by csreddy** [comment]
If I do `npm run express` then app completely fails with below error in chrome console:
```bash
GET http://localhost:8080/__build__/common.js 
(index):39 GET http://localhost:8080/__build__/angular2.js 404 (Not Found)
(index):41 GET http://localhost:8080/__build__/app-simple.js 404 (Not Found)
```

**Comment by gdi2290** [comment]
can you try  `NODE_ENV=development npm run express`

**Comment by csreddy** [comment]
that fixes the problem! Thanks for the quick response and keep up the great work!

**Comment by gsans** [comment]
Can you update the building/instructions so we don't all run into the same issue after installing?

**Comment by NathanWalker** [comment]
@gsans @gdi2290 This PR https://github.com/angular-class/angular2-webpack-starter/pull/34 also updates the build/instructions to include that fix :+1:
