### ISSUE TITLE
refactor repo to use RxNext

### ISSUE THREAD

**Issue by gdi2290** [angular-class/angular2-webpack-starter#40]
RxNext uses the ES7 spec

**Comment by SekibOmazic** [comment]
@gdi2290 You mean https://github.com/ReactiveX/RxJS (which is pre-alpha)?

**Comment by gdi2290** [comment]
yeah I hear it's been called RxNext

**Comment by SekibOmazic** [comment]
I'd wait for https://github.com/ReactiveX/RxJS/pull/120 to get merged because it's a big one. Or even wait for https://github.com/ReactiveX/RxJS/issues/100 because we get more operators (but not all).

**Comment by gdi2290** [comment]
I'm going to close this until angular itself uses it. Currently RxNext is Rx 4.x and we're still on 3.x
