### ISSUE TITLE
Help with establishing workflow: WebPack, TS, LESS, Mocks, config.json

### ISSUE THREAD

**Issue by kburson** [angular-class/angular2-webpack-starter#49]
@gdi2290 , with regards to our discussion on gitter, Can you help me establish the following workflow using this project structure?  

Deployment
 * Deploy 1 or more bundles to CDN
 * Deploy index.html and config.json to server.

Bundles are packaged dependencies:
 * Typescript with classes and imports transpiled to ES5, minified and obfuscated.
 * LESS with @imports transpiled to CSS and minified
 * vendor minified js and css.
 * images (png,gif,jpg…) minified.
 * fonts and svg

Build conditional resources:
 *    if(MOCKS) then load local mock service definitions (using E2E_Mock ) and json mock data files

Server configuration file (config.json)     
 * Compile config.json file for target server
   * modify target service urls specific to deployment server.
     * Compile to a tmp folder for access during local testing.
     * copy to dist folder on production build.
   * how to load asynchronously outside of the bundle.

Dev Workflow:
 * compile config.json to temp folder
 * start webpack-dev-server
 * load app in browser
 * On change to ts or less files
   * Run lint on source file
   * re-transpile that file and reload into dev-server cache
   * include sourcemaps for debugging

Ready to commit:
 * Run karma tests against PhantomJS with code coverage ( Istanbul? 
   * If failure use karma against chrome to debug using webstorm xdebug remote.
 * run plato reports with linting for ts and less.
 * Package for deployment
 * run protractor tests against dist bundles

Package for Deployment:
 * Build distribution bundle with cache busting and asset minification
 * copy index.html to dist folder
 * compile config.json for staging and production.
   * Deployment to server should use the same bundle but specific config.json.

**Comment by kburson** [comment]
The main trick I am running into is the conditional compile using E2E_Mocks or not, and the separate config.json file that needs to be compiled from a global config file and local environment values.

I am currently using ES6, but I want to migrate to Typescript, although that can wait until I have the rest of it working.

I am currently using Angular 1.4.x and need to establish working patterns with this before I migrate to A2.
I will be looking into the Universal Angular, using Meteor as an isomorphic server side component, in order to enable use of A2 with legacy browsers ( IE8 ), but that is to support my other teams, my current team can target the latest of firefox.

**Comment by gdi2290** [comment]
@kburson can you elaborate more on the `if (MOCKS) {}` blocks?

**Comment by kburson** [comment]
During development I often have the UI built before the data services team is ready to serve data.  to facilitate development of the UI I use the Angular-Mocks library, specifically the E2E_Mocks to capture all outgoing http requests and provide canned responses.  This allows me to show a fully functional site using a series of preset json data files served up from canned responses using the mocked service calls.

My understanding with webpack is that you can have an environment variable, read or passed in, that can be used as a build time constant that determines whether or not to include specific blocks, and whether or not to include specified resources in the bundle.

If I wanted to build and test with mocked services I would pass in the MOCK setting (i.e.  USE_MOCKS=true).  This would cause the mockd data json files to be loaded along with the mock service definitions (dynamic mock defs for the expected behavior).

It is simply a conditional compile.

This would also be helpful in a production/dev build to use pre-minified vendor files or not.

**Comment by kburson** [comment]
I am struggling with the balance of present functionality vs future.  JSPM with SystemJS seems to me the better system.  SystemJS is a polyfill module system until the browsers catchup with the ES2015 specs, which should be fairly shortly.  This polyfill can be used long term to support legacy browsers but can be dropped in the near future when the evergreen browsers catchup with ES2015.

JSPM is a superior package management system that can roll npm, bower and github all into one system.  Very nice, very organized, self managing.

SystemJS comes with a Bundler, as does JSPM.  The problem I have with the bundler is that, while it can transpile ES6 to ES5 using traceur or babel, it cannot transpile LESS to CSS.

Using LESS files that import a common parent with standard definitions (variables for fonts, colors, sizes and specific mixins) is very helpful.  

It is possible to pre-compile the LESS files and store the compiled version in a build folder, along with a pre-compiled config file defining the application resources for the specific environment. 

During testing the SystemJS can load and transpile all JS resources, but needs to load the pre-transpiled  config.json and app.css (from *.LESS) from a build folder, along with the un-minified versions of  veddor libraries from the JSPM_Components folder hierarchy.

For deployment the SystemJS (or JSPM) can bundle all the necessary resource, selecting the minified versions of vendor libs, as well as pre-compiled versions of all ES6/LESS resources, and any identified fonts and images.

The trick is, how to make this efficient so that you do not have to pre-compile and copy all files to a build folder for testing, then bundles those files for production..

While webpack has a LESS transpiler (loader) available, JSPM (SystemJS) does not.

With Webpack development workflow I can have all the JS/LESS files transpiled on the fly and loaded into an in-memory server (webpack-dev-server) that can hot-swap out individual files as needed during development.  This is a very efficient system.

When testing is complete the same config can be used to bundle these resources into a single JS file ready for deployment thru a CDN, with the config.json and index.html served from the production server (to establish CORS origin).

SystemJS/JSPM does not allow this workflow.  I am still investigating it.

Any thoughts between the two systems ?

**Comment by jarnix** [comment]
no

**Comment by gdi2290** [comment]
there's a lot of good points here but I may have to make another starter repo for fullstack angular2 to include a lot of this

**Comment by gdi2290** [comment]
I'm going to move all these features into the fullstack-angular2-starter repo and keep this repo to simply be a webpack starter

**Comment by simonmcl** [comment]
@gdi2290 I've just started using this starter. I can see that there is a "mock-data" folder in the repo now. I'm struggling to understand its use as it doesn't seem to be documented anywhere. Is this just a placeholder file, where I need to write it and read from it as I see fit?

Or is there a tool / library that is expecting it to be there, named like that and the data in a certain format?

Are there links / documents / examples about this anywhere?
