### ISSUE TITLE
production build produces source map file with different name

### ISSUE THREAD

**Issue by mmrath** [angular-class/angular2-webpack-starter#52]
Build produces file with name __build__/angular2.min.js.min.js.map instead of __build__/angular2.min.js.map

**Comment by gdi2290** [comment]
this code snippet might be the problem
https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js#L193...L197

**Comment by gdi2290** [comment]
thanks, should be fixed via https://github.com/angular-class/angular2-webpack-starter/commit/c2aa659894ce3d69518d9350d50f10e05daeeed7
