### ISSUE TITLE
Lots of warnings?

### ISSUE THREAD

**Issue by ctindel** [angular-class/angular2-webpack-starter#63]
I did a fresh clone and npm start, and there are tons of warnings everywhere.  For example:

WARNING in ./app.ts
(6,58): Cannot find module 'angular2/angular2'. (2307)

WARNING in ./app.ts
(7,9): Module '"angular2/router"' has no exported member 'RouteConfig'. (2305)

WARNING in ./app.ts
(14,48): Cannot find module 'angular2/angular2'. (2307)

WARNING in ./bootstrap.ts
(4,25): Cannot find module 'angular2/angular2'. (2307)

WARNING in ./bootstrap.ts
(11,29): Cannot find module 'angular2/angular2'. (2307)

WARNING in ../typings/ng2.d.ts
(34,32): Cannot find name 'List'. (2304)

WARNING in ../typings/ng2.d.ts
(329,33): Cannot find name 'List'. (2304)

WARNING in ../typings/ng2.d.ts
(358,33): Cannot find name 'List'. (2304)

I'm guessing this has to do with forgetting to include some typescript files somewhere, but I'm not sure.

**Comment by gdi2290** [comment]
can you run `tsd install`

**Comment by ctindel** [comment]
I don't have any sort of tsd command in my path.  I tried running ./node_modules/.bin/tsd install which did do something but the errors still occur.

**Comment by gdi2290** [comment]
ya try `./node_modules/.bin/tsd install` and `npm start`

**Comment by gdi2290** [comment]
@ctindel sorry I found the problem. this was due to tsd publishing breaking changes as patched versions and then they tried to revert them

**Comment by ctindel** [comment]
That doesn't change anything.

I also tried doing a global install of tsd but that doesn't change anything either.

I'm also trying add in the LoggedInRouterOutlet stuff from the auth0 sample since your sample doesn't have authentication stuff yet.  So I created a LoggedInOutlet.ts in the same directory as app.ts and even though they both start with this line:

/// <reference path="../typings/_custom.d.ts" />

I'm still getting this warning/error at npm start time:

WARNING in ./LoggedInOutlet.ts
(3,82): Cannot find module 'angular2/angular2'. (2307)

I feel pretty comfortable with angular2 code at the moment but all this custom typing stuff is really unclear to me what is going on behind the scenes or why any of it is needed, and it seems like every sample angular2 application out there does it totally differently.

At this point I'm just trying to get your sample to start without any warnings or errors.  :)

Thanks for your help!

**Comment by gdi2290** [comment]
@ctindel type in `./node_modules/.bin/tsd link`

**Comment by ctindel** [comment]
OK calling that tsd link seems to have removed some warnings.  Is that just something you have to do every time, or one time?

**Comment by gdi2290** [comment]
just once

**Comment by ctindel** [comment]
OK.  I have a few more questions which I think are related.  Why am I not able to do this:

```
import {Http, Headers} from 'angular2/http';
```

It gives me this error:

Error: Cannot resolve module 'angular2/http'

It seems like I need to make this ngHttp/http, but I can't figure out why?

Also, I tried adding this to my App class:

```
@RouteConfig([
  new Route({ path: '/',       redirectTo: '/home' }),
  new Route({ path: '/home',   as: 'home',   component: Home }),
  new Route({ path: '/login',  as: 'login',  component: Login }),
  new Route({ path: '/signup', as: 'signup', component: Signup })
])
```

But I get these errors:

WARNING in ./app.ts
(31,3): Supplied parameters do not match any signature of call target. (2346)

WARNING in ./app.ts
(32,3): Supplied parameters do not match any signature of call target. (2346)

WARNING in ./app.ts
(33,3): Supplied parameters do not match any signature of call target. (2346)

WARNING in ./app.ts
(34,3): Supplied parameters do not match any signature of call target. (2346)

**Comment by gdi2290** [comment]
@ctindel can you update this file to latest 
https://github.com/angular-class/angular2-webpack-starter/blob/master/src/typings/ng2.d.ts

**Comment by ctindel** [comment]
No, the warnings still happen.

**Comment by gdi2290** [comment]
the problem is due to an error in typings that angular provided. If you update the webpack config then it will ignore that warning
https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js

the `angular/http` problem will be available next release so at the moment we have to include a local version

**Comment by ctindel** [comment]
Is ignoring the warning really the best solution?  Or are we just needing to wait for the angular team to update the typings in tsd or something?

**Comment by gdi2290** [comment]
ignoring and waiting for the angular team to fix it seems to be the best solution at the moment :/

**Comment by ctindel** [comment]
OK, sounds good.

Can you do me a favor?  Can you pull https://github.com/ctindel/reader and go into the www directory and run npm install && npm start?

I am getting a really bizarre NoAnnotationError "Cannot resolve all parameters for DomRenderer" error that I have no idea what is going on or even how to debug it because the stack in the javascript console doesn't tell me much of anything.  

This source is basically just a fork of your app, plus I tried to start adding the LoggedInRouter stuff.

**Comment by gdi2290** [comment]
@ctindel yeah that error is due to the `reflect-metadata` version 
https://github.com/angular-class/angular2-webpack-starter/commit/a753691ca5253ec546b780ff80ccb56e6cfa98b2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R47

delete reflect-metadata in node_modules and install that version

**Comment by gdi2290** [comment]
@ctindel I updated the repo to alias `angular2/http` and fixed the reflect-metadata issue
