### ISSUE TITLE
NoAnnotationError

### ISSUE THREAD

**Issue by ctindel** [angular-class/angular2-webpack-starter#64]
I just did a fresh clone of your repo and an npm install, and I am seeing the exact same NoAnnotationError in the Chrome developer console.  This is chrome version 44.0.2403.157 (64-bit) on osx.

I also see it in an up to date version of Google Chrome Canary.

Are you not seeing these?

**Comment by gdi2290** [comment]
@ctindel ya I see the error again :/ sorry I'm looking into it again

**Comment by gdi2290** [comment]
can you git clone the repo again and run `npm run clean-start`

**Comment by ctindel** [comment]
Yeah that seems to have fixed it.  I see what you changed, the problem was just that some angular files were missing from the webpack bundle?

**Comment by gdi2290** [comment]
yeah that might have been the case thanks for pinging me about it :+1:

**Comment by ctindel** [comment]
Thanks for keeping an example repo that tracks the changes in angular2 so quickly!
