### ISSUE TITLE
generate typescript source map with loader:'typescript-simple' 

### ISSUE THREAD

**Issue by Gabriel0402** [angular-class/angular2-webpack-starter#90]
I wanted to debug with vscode, so I'll need to generate source map for the ts files. But the ts loader is using 'typescript-simple' which didn't support generate source map. Is there anyway I can generate source map for it instead of generate *.js.map files? Or can I change the loader to some other source map supported loaders? Thanks!

**Comment by ceolter** [comment]
if you want the source maps, then simple build using 'gulp'

mentioned on the main page, the two different gulp tasks to run, 'default' and 'release'
https://github.com/ceolter/ag-grid

**Comment by ceolter** [comment]
(please ignore my activity on this thread, i got mixed up between projects!)

**Comment by gdi2290** [comment]
@Gabriel0402 can you change this line of code
https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js#L35...L38
```
devtool: env({
    'development': 'eval',
    'all': 'source-map'
  }),
```
change to 
```
devtool: 'source-map',
```

**Comment by Gabriel0402** [comment]
@gdi2290 Thanks!
