### ISSUE TITLE
No router example working

### ISSUE THREAD

**Issue by plopinou** [angular-class/angular2-webpack-starter#92]
Hello,
Before everything else, I thank you very much for providing a starter pack to what seem to me to be the future best angular 2 workflow when the final will be released.
I tried multiple examples and everything seem to work fine, except for the "large app" example, which is also the only one featuring a router.
I managed to correct all the errors, but the router is still not functional with the error "EXCEPTION: No provider for Token RouterPrimaryComponent! (RouterLink -> Router -> Token RouterPrimaryComponent)".

I also tried to wrap with webpack the angular 2 seed sample from the repo at https://github.com/mgechev/angular2-seed , but for whatever reason, vars in {{}} aren't interpreted in the about or home templates, as if some sort of $digest wasn't there (even if it doesn't exist anymore in angular 2).

Is there any way to see a working router example with multiple paths using webpack and angular 2 ?
Even a basic plunker would be ok :)

**Comment by chriscurnow** [comment]
I have submitted a pull request that fixes most of the errors – but this has mainly been through trial and error. I still haven't got router working.
